class_name CapybaraRushPaths
extends RefCounted

## Capybara Rush 专用资源根（勿与星火信使 ModelPaths 混用）

const ROOT := "res://assets/maps/route_levels/capybara_rush/"
const MODELS := ROOT + "models/"
const LEVELS := ROOT + "levels/"

const CHARACTERS := MODELS + "characters/"
const OBSTACLES := MODELS + "obstacles/"
const ENVIRONMENT := MODELS + "environment/"
const PROPS := MODELS + "props/"

const CAPYBARA_BASE := CHARACTERS + "capybara_base.glb"
## Tripo quadruped 绑定版（含 tripo::Head_0，用于只转头）
const CAPYBARA_BASE_RIGGED := CHARACTERS + "capybara_base_rigged.glb"
const QINGQING := CHARACTERS + "qingqing.glb"
const QINGQING_RIGGED := CHARACTERS + "qingqing_rigged.glb"
const LITTLE_MONSTER := CHARACTERS + "little_monster.glb"
const LITTLE_MONSTER_RIGGED := CHARACTERS + "little_monster_rigged.glb"
const LITTLE_RABBIT := CHARACTERS + "little_rabbit.glb"
const LITTLE_RABBIT_RIGGED := CHARACTERS + "little_rabbit_rigged.glb"
const SHIBA := CHARACTERS + "shiba.glb"
const SHIBA_RIGGED := CHARACTERS + "shiba_rigged.glb"
const BIRD := CHARACTERS + "bird.glb"
const BIRD_RIGGED := CHARACTERS + "bird_rigged.glb"
const MOUSE := CHARACTERS + "mouse.glb"
const MOUSE_RIGGED := CHARACTERS + "mouse_rigged.glb"
const SLOTH := CHARACTERS + "sloth.glb"
const SLOTH_RIGGED := CHARACTERS + "sloth_rigged.glb"
const TINY_PLANET := CHARACTERS + "tiny_planet.glb"
const TINY_PLANET_RIGGED := CHARACTERS + "tiny_planet_rigged.glb"
const BEAR := CHARACTERS + "bear.glb"
const BEAR_RIGGED := CHARACTERS + "bear_rigged.glb"
const COW := CHARACTERS + "cow.glb"
const COW_RIGGED := CHARACTERS + "cow_rigged.glb"
const CAPYBARA_PILOT := CHARACTERS + "capybara_pilot.glb"
const FENCE_PICKET := OBSTACLES + "fence_picket.glb"
const FENCE_HALF := OBSTACLES + "fence_half.glb"
const HAY_BALE := ENVIRONMENT + "hay_bale.glb"
const TREE_SAKURA := ENVIRONMENT + "tree_sakura.glb"
const NEON_SIGN_POST := ENVIRONMENT + "neon_sign_post.glb"
const STEAM_VENT := ENVIRONMENT + "steam_vent.glb"
const FENCE_PASTURE := OBSTACLES + "fence_pasture.glb"
const LANTERN_BARRIER := OBSTACLES + "lantern_barrier.glb"
const NEON_CONE := OBSTACLES + "neon_cone.glb"
const VOLCANIC_BLOCK := OBSTACLES + "volcanic_block.glb"
const STONE_LANTERN_BARRIER := OBSTACLES + "stone_lantern_barrier.glb"
const TRAFFIC_CONE := OBSTACLES + "traffic_cone.glb"
const ROCK_EDGE := ENVIRONMENT + "rock_edge.glb"
const TREE_LOLLIPOP := ENVIRONMENT + "tree_lollipop.glb"
const PALM_TREE := ENVIRONMENT + "palm_tree.glb"
const CLOUD_FLUFFY := ENVIRONMENT + "cloud_fluffy.glb"
const BUSH_ROUND := ENVIRONMENT + "bush_round.glb"
const FINISH_ARCH := PROPS + "finish_arch.glb"
const PICKUP_GLOW_PAD := PROPS + "pickup_glow_pad.glb"
const SPACESHIP := PROPS + "spaceship.glb"
const BOOST_PACK := PROPS + "boost_pack.glb"
const SPEED_ORB := PROPS + "speed_orb.glb"
const STEP_PLATFORM := ENVIRONMENT + "step_platform.glb"
const SPEED_LANE := PROPS + "speed_lane.glb"
const WATERMELON_SLICE := PROPS + "watermelon_slice.glb"
const TREASURE_CHEST := PROPS + "treasure_chest.glb"
const FRUIT_BANANA := PROPS + "banana.glb"
const FRUIT_PINEAPPLE := PROPS + "pineapple.glb"
const FRUIT_DURIAN := PROPS + "durian.glb"
const FRUIT_APPLE := PROPS + "apple.glb"
const FRUIT_ORANGE := PROPS + "orange.glb"

const AUDIO := ROOT + "audio/"
const BGM_RUN := AUDIO + "bgm_run.wav"
const SFX_FRUIT := AUDIO + "sfx_fruit.wav"
const SFX_HIT := AUDIO + "sfx_hit.wav"
const SFX_PICKUP := AUDIO + "sfx_pickup.wav"
